### ISSUE TITLE
Indicated procedure to build PLS doesn't work

### ISSUE THREAD

**Issue by Firefly35** [genericptr/pascal-language-server#71]
Calling lazbuild src/standard/pasls.lpi gives the following error:
Error: (lazbuild) Broken dependency: lspprotocol

After opening of lspprotocol.lpk in lazarus in order for lazbuild to find it, I still get an error:
Error: (lazbuild) Broken dependency: lspprotocol 1.0->jcfnogui

I expect to be able to build the pascal-language-server in the command line with the indications available in the repository README.md

**Comment by genericptr** [comment]
I've been using makefiles to build and lazbuild is not working on my Mac right now. Maybe @mvancanneyt will have some ideas since he's an actual Lazarus user.

**Comment by Firefly35** [comment]
Maybe the makefiles could be in the repository if they allow to build the pascal-language-server ?

**Comment by genericptr** [comment]
ok I think this is fixed now, can you pull again and see if lazbuild works? Thanks!

**Comment by Firefly35** [comment]
Indeed it is now working as expected, thanks
