### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by chunqian** [genericptr/pascal-language-server#79]
Compile with Makefile, I found error:
```bash
/Users/tim/Downloads/.env/pascal/pascal-language-server/src/serverprotocol/PasLS.General.pas(445,24) Error: (5038) identifier idents no member "SortMethodForCompletion"
/Users/tim/Downloads/.env/pascal/pascal-language-server/src/serverprotocol/PasLS.General.pas(445,49) Error: (5000) Identifier not found "icsScopedAlphabetic"
PasLS.General.pas(541) Fatal: (10026) There were 2 errors compiling module, stopping
Fatal: (1018) Compilation aborted
make[1]: *** [main.ppu] Error 1
make: *** [build-pasls] Error 2
```

**Comment by genericptr** [comment]
@mvancanneyt Maybe a regression from the last PR? BTW, are you getting notifications on this repo? Sorry but I haven't had time to test your recent changes extensively so it's very possible things slip through.

**Comment by mvancanneyt** [comment]
You need the latest trunk version of Lazarus to compile this.

They changed the interface of the codetools :cry:

**Comment by chunqian** [comment]
@genericptr  @mvancanneyt With the latest trunk version of Lazarus, Compile OK. But pasls can't works, before the last PR, it works well.

**Comment by mvancanneyt** [comment]
Strange, because I tested it and it worked OK here. 
Can you please describe the error you get ?

**Comment by chunqian** [comment]
@mvancanneyt 
I think the problem is  ApplySettings procedure not used.
<img width="583" alt="image" src="https://github.com/genericptr/pascal-language-server/assets/13447930/9364ee0c-c947-4bca-b015-77223f58935d">
Fix it.
<img width="788" alt="image" src="https://github.com/genericptr/pascal-language-server/assets/13447930/2d7e5016-6b06-42a8-8967-a3a6a35b35de">
