### ISSUE TITLE
Cannot compile lspprotocol and lspserver

### ISSUE THREAD

**Issue by LinusDenning2001** [genericptr/pascal-language-server#89]
![Screenshot from 2024-09-06 15-53-46](https://github.com/user-attachments/assets/830b5730-04ba-4753-87a1-f7529f23de5f)
I wanted to use this lsp for nvim.
After downloading Lazarus and fpc-3.2.0 and then following the building steps I get the following compile error.

Identifier not found "jdoIgnoreNulls"

after looking for the declaration I assume is should be in fpjsonrtti, however it cannot be found

**Comment by mvancanneyt** [comment]
You need to compile this with the trunk version of FPC. The release version of FPC cannot be used to compile the LSP project

**Comment by LinusDenning2001** [comment]
![Screenshot from 2024-09-11 13-24-10](https://github.com/user-attachments/assets/dbf7bf2d-21cf-4251-a117-1204e89b8691)

I'm still having issues when using the trunk resources found in the [gitlab](https://gitlab.com/freepascal.org/fpc/source.git)

**Comment by mvancanneyt** [comment]
I was compiling my fork, and that worked.
I updated it, and now I can reproduce it, seems to be result of the recent merge. I will look at it.

**Comment by mvancanneyt** [comment]
I undid the merge. The merged functionality was present in paslsproxy, so nothing is lost.

**Comment by LinusDenning2001** [comment]
I am still having an issue compiling PasLS.TextLoop used by lspprotocol with the same issue as before. Could you direct me on how you fixed the issue?

**Comment by mvancanneyt** [comment]
I removed the code. Line 264 in PasLS.TextLoop no longer exists, as you can check in the repo...

**Comment by LinusDenning2001** [comment]
I have now managed to compile the lsp

One thing to note is that I did have to install the SQLite developer tools to finally get it working (libsqlite3-dev)

Many thanks for your time
